### ISSUE TITLE
Suggestion Recolor sliders to show on or off state.

### ISSUE THREAD

**Issue by Psyda** [lap00zza/9anime-Companion#67]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Currently the checkboxes are somewhat confusing on the dashboard page.
You also can only click on the circle.

Video clip of before/after css fix: https://streamable.com/0wp7l

Attached a css fix you can apply to an inspector stylesheet. Mind you it's a bit hacky as I needed it to hide some of the original css.
```css
.settings-checkbox{
    position: relative; 
    width: 55px;
    -webkit-user-select:none; 
    -moz-user-select:none; 
    -ms-user-select: none;
    background-color: unset;
}
.settings-checkbox input[type=checkbox]{
    display: none;
    visibility: visible;
}
.settings-checkbox label{
    display: block;
    overflow: hidden;
    cursor: pointer;
    height: 20px;
    padding: 0;
    line-height: 20px;
    border: 2px solid white;
    border-radius: 20px;
    background-color: darkgrey !important;
    transition: background-color 0.3s ease-in;
}
.settings-checkbox label:before{
    content: "";
    display: block; width: 20px; margin: 0px;
    background: white;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.37);
    position: absolute; top: 0; bottom: 0;
    right: 33px;
    border: 2px solid white; border-radius: 20px;
    transition: all 0.3s ease-in 0s; 
    width: 26px;
    height: 26px;
}
.settings-checkbox input[type=checkbox]:checked + label{
    background-color: deepskyblue !important;
}
.settings-checkbox input[type=checkbox]:checked + label, .settings-checkbox input[type=checkbox]:checked + label:before{
   border-color: deepskyblue;
   box-shadow: unset;
}
.settings-checkbox input[type=checkbox]:checked + label:before{
    right: 0px;
}
.settings-checkbox label{
    width: 50px;
    height: 26px;
    position: initial;
}
```
